ManageBundle\Entity\Area:
    type: entity
    table: area
    indexes:
        name:
            columns:
                - name
        pid:
            columns:
                - pid
        level:
            columns:
                - level
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        pid:
            options:
                comment: 父级id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        code:
            options:
                comment: 代码
                unsigned: false
            nullable: false
            type: integer
            length: 10
        citycode:
            options:
                comment: 城市代码
                unsigned: false
            nullable: false
            type: integer
            length: 10
        level:
            options:
                comment: 等级
                unsigned: false
            nullable: false
            type: smallint
            length: 3
        notes:
            options:
                comment: 下级数量
                unsigned: false
            nullable: false
            type: integer
            length: 10
        map:
            options:
                comment: 地图
                unsigned: false
            nullable: false
            type: string
            length: 100
        polyline:
            options:
                comment: 地图范围
                unsigned: false
            nullable: false
            type: text
            length: 0
        checked:
            options:
                comment: 审核
                unsigned: false
            nullable: false
            type: integer
            length: 10
        type:
            options:
                comment: 分站地区
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        theme:
            options:
                comment: 分站主题
                unsigned: false
            nullable: false
            type: integer
            length: 10
        main:
            options:
                comment: 主控台
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        binary_tree:
            options:
                comment: '二叉树标识,1为启用'
                unsigned: false
            nullable: false
            type: boolean
        left_node:
            options:
                comment: 左节点
                unsigned: false
            nullable: false
            type: integer
        right_node:
            options:
                comment: 右节点
                unsigned: false
            nullable: false
            type: integer
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
