ManageBundle\Entity\Authtest:
    type: entity
    table: authtest
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 名称
                unsigned: false
            nullable: false
            type: string
            length: 100
        title:
            options:
                comment: 备注
                unsigned: false
            nullable: false
            type: text
            length: 0
        pid:
            options:
                comment: 上级id
                unsigned: false
                default: '2'
            nullable: false
            default: '2'
            type: integer
            length: 10
        left_node:
            options:
                comment: 左连接
                unsigned: false
            nullable: false
            type: integer
            length: 10
        right_node:
            options:
                comment: 右连接
                unsigned: false
            nullable: false
            type: integer
            length: 10
        binary_tree:
            options:
                comment: 二叉树标识
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        content:
            options:
                comment: 内容
                unsigned: false
            nullable: false
            type: text
            length: 0
        pic:
            options:
                comment: 图片
                unsigned: false
            nullable: false
            type: string
            length: 100
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
