ManageBundle\Entity\InterIntention:
    type: entity
    table: inter_intention
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        models:
            options:
                comment: 模型
                unsigned: false
            nullable: false
            type: string
            length: 100
        uid:
            options:
                comment: 会员id
                unsigned: false
            nullable: false
            type: integer
            length: 100
        name:
            options:
                comment: 名称
                unsigned: false
            nullable: false
            type: string
            length: 100
        tel:
            options:
                comment: 电话
                unsigned: false
            nullable: false
            type: string
            length: 100
        aid:
            options:
                comment: 房源id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        checked:
            options:
                comment: 审核
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        user_agent:
            options:
                comment: 浏览器类型
                unsigned: false
            nullable: false
            type: text
            length: 0
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
