ManageBundle\Entity\Integral:
    type: entity
    table: integral
    indexes:
        ename:
            columns:
                - ename
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 积分名称
                unsigned: false
            nullable: false
            type: string
            length: 100
        unit:
            options:
                comment: 单位
                unsigned: false
            nullable: false
            type: string
            length: 100
        initial:
            options:
                comment: 初始值
                unsigned: false
            nullable: false
            type: string
            length: 100
        sid:
            options:
                comment: 来源积分
                unsigned: false
            nullable: false
            type: integer
            length: 10
        scurrency:
            options:
                comment: 来源积分数值
                unsigned: false
            nullable: false
            type: integer
            length: 10
        eid:
            options:
                comment: 兑换积分
                unsigned: false
            nullable: false
            type: integer
            length: 10
        ecurrency:
            options:
                comment: 兑换积分数值
                unsigned: false
            nullable: false
            type: integer
            length: 10
        type:
            options:
                comment: 类别
                unsigned: false
            nullable: false
            type: string
            length: 100
        ename:
            options:
                comment: 标识
                unsigned: false
            nullable: false
            type: string
            length: 100
        paying:
            options:
                comment: 是否用于支付
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        issystem:
            options:
                comment: 0可以删除1不可删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
