ManageBundle\Entity\MemGroup:
    type: entity
    table: mem_group
    indexes:
        aid:
            columns:
                - aid
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        valid:
            options:
                comment: 会员分类有效期
                unsigned: false
            nullable: false
            type: integer
            length: 10
        overdue:
            options:
                comment: 过期后转到其它组
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        ico:
            options:
                comment: 会员类型图标
                unsigned: false
            nullable: false
            type: text
            length: 100
        form_id:
            options:
                comment: 表单
                unsigned: false
            nullable: false
            type: integer
            length: 10
        autoinit:
            options:
                comment: 注册自动成为本分类会员
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        name:
            options:
                comment: 会员组名称
                unsigned: false
            nullable: false
            type: string
            length: 100
        aid:
            options:
                comment: 会员分类id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        mincurrency:
            options:
                comment: 最低积分
                unsigned: false
            nullable: false
            type: integer
            length: 10
        maxcurrency:
            options:
                comment: 最高积分
                unsigned: false
            nullable: false
            type: integer
            length: 10
        role:
            options:
                comment: 角色绑定
                unsigned: false
            nullable: false
            type: string
            length: 100
        issystem:
            options:
                comment: '0为可删除 1为不可删除'
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
