ManageBundle\Entity\Rtconfig:
    type: entity
    table: rtconfig
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 方案名称
                unsigned: false
            nullable: false
            type: string
            length: 100
        price:
            options:
                comment: 总价格
                unsigned: false
            nullable: false
            type: float
            length: 100
        value:
            options:
                comment: '刷新次数,置顶天数'
                unsigned: false
            nullable: false
            type: integer
            length: 10
        type:
            options:
                comment: '1=置顶, 2=刷新'
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        time:
            options:
                comment: 刷新时间
                unsigned: false
            nullable: false
            type: string
            length: 100
        unit:
            options:
                comment: 单价
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        discount:
            options:
                comment: 折扣
                unsigned: false
            nullable: false
            type: string
            length: 100
        issystem:
            options:
                comment: '0为可删除 1为不可删除'
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        number:
            options:
                comment: 刷新次数
                unsigned: false
            nullable: false
            type: integer
            length: 10
        intervals:
            options:
                comment: 间隔
                unsigned: false
            nullable: false
            type: integer
            length: 10
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
