ManageBundle\Entity\Test:
    type: entity
    table: test
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 测试名字
                unsigned: false
            nullable: false
            type: string
            length: 20
        areaid:
            options:
                comment: 区域
                unsigned: false
            nullable: false
            type: integer
            length: 5
        fly:
            options:
                comment: 飞
                unsigned: false
                default: '4'
            nullable: false
            default: '4'
            type: string
            length: 2
        run:
            options:
                comment: 跑啊pao
                unsigned: false
                default: '4'
            nullable: false
            default: '4'
            type: integer
            length: 3
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
