ManageBundle\Entity\TopicArc:
    type: entity
    table: topic_arc
    indexes:
        fromid:
            columns:
                - fromid
        cate_pushs:
            columns:
                - cate_pushs
        aid:
            columns:
                - aid
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        upvideo:
            options:
                comment: 视频链接
                unsigned: false
            nullable: false
            type: string
            length: 100
        fromid:
            options:
                comment: 文档id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        cate_pushs:
            options:
                comment: 推荐分类
                unsigned: false
            nullable: false
            type: string
            length: 100
        models:
            options:
                comment: 模型
                unsigned: false
            nullable: false
            type: string
            length: 100
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        name:
            options:
                comment: 标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        aid:
            options:
                comment: 专题id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        form:
            options:
                comment: 表单
                unsigned: false
            nullable: false
            type: string
            length: 100
        checked:
            options:
                comment: 审核
                unsigned: false
                default: '1'
            nullable: false
            default: '1'
            type: integer
            length: 10
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
