ManageBundle\Entity\UserAuth:
    type: entity
    table: user_auth
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 认证标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        thumb:
            options:
                comment: 认证图片
                unsigned: false
            nullable: false
            type: text
            length: 0
        usertype:
            options:
                comment: 会员类型
                unsigned: false
            nullable: false
            type: string
            length: 100
        integral:
            options:
                comment: 奖励积分类型
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        num:
            options:
                comment: 奖励积分数量
                unsigned: false
            nullable: false
            type: integer
            length: 10
        remark:
            options:
                comment: 备注
                unsigned: false
            nullable: false
            type: string
            length: 100
        form:
            options:
                comment: 指定表单
                unsigned: false
            nullable: false
            type: integer
            length: 10
        autochecked:
            options:
                comment: 自动审核0为否1为是
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        listen:
            options:
                comment: 自动审核0为否1为是
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
