ManageBundle\Entity\Wxdefault:
    type: entity
    table: wxdefault
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        token:
            options:
                comment: token
                unsigned: false
            nullable: false
            type: string
            length: 200
        reply_default:
            options:
                comment: 微信默认回复
                unsigned: false
            nullable: false
            type: text
            length: 0
        subscribe_default:
            options:
                comment: 微信关注默认回复
                unsigned: false
            nullable: false
            type: text
            length: 0
        unsubscribe_default:
            options:
                comment: 取消关注默认回复
                unsigned: false
            nullable: false
            type: text
            length: 0
        transmit:
            options:
                comment: 多客服触发
                unsigned: false
            nullable: false
            type: string
            length: 255
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
