HouseBundle\Entity\Ask:
    type: entity
    table: ask
    indexes:
        name:
            columns:
                - name
        category:
            columns:
                - category
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        currency:
            options:
                comment: 高额悬赏
                unsigned: false
            nullable: false
            type: integer
            length: 10
        thumb:
            options:
                comment: 缩略图
                unsigned: false
            nullable: false
            type: text
            length: 0
        name:
            options:
                comment: 标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        content:
            options:
                comment: 问题
                unsigned: false
            nullable: false
            type: text
            length: 0
        keywords:
            options:
                comment: 标签
                unsigned: false
            nullable: false
            type: text
            length: 0
        category:
            options:
                comment: 栏目分类id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        solved:
            options:
                comment: 问题解决状态
                unsigned: false
            nullable: false
            type: smallint
            length: 100
        checked:
            options:
                comment: 问答审核
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        clicks:
            options:
                comment: 点击
                unsigned: false
            nullable: false
            type: integer
            length: 10
        uid:
            options:
                comment: 会员id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        models:
            options:
                comment: 模型
                unsigned: false
                default: ask
            nullable: false
            default: ask
            type: string
            length: 100
        asknum:
            options:
                comment: 答案数量
                unsigned: false
            nullable: false
            type: integer
            length: 10
        abstract:
            options:
                comment: 摘要
                unsigned: false
            nullable: false
            type: text
            length: 0
        jinghua:
            options:
                comment: 精华
                unsigned: false
            nullable: false
            type: integer
            length: 10
        area:
            options:
                comment: 区域
                unsigned: false
            nullable: false
            type: integer
            length: 10
        user_agent:
            options:
                comment: 浏览器类型
                unsigned: false
            nullable: false
            type: text
            length: 0
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
