HouseBundle\Entity\AskReport:
    type: entity
    table: ask_report
    indexes:
        aid:
            columns:
                - aid
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        uid:
            options:
                comment: 会员id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        jbaotype:
            options:
                comment: 举报类型
                unsigned: false
            nullable: false
            type: string
            length: 100
        name:
            options:
                comment: 姓名
                unsigned: false
            nullable: false
            type: string
            length: 100
        content:
            options:
                comment: 问题说明
                unsigned: false
            nullable: false
            type: text
            length: 0
        aid:
            options:
                comment: 问答id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        models:
            options:
                comment: 模型
                unsigned: false
            nullable: false
            type: string
            length: 100
        checked:
            options:
                comment: 审核
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        user_agent:
            options:
                comment: 浏览器类型
                unsigned: false
            nullable: false
            type: text
            length: 0
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
