HouseBundle\Entity\AuthFirewall:
    type: entity
    table: auth_firewall
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 名称
                unsigned: false
            nullable: false
            type: string
            length: 100
        path:
            options:
                comment: 规则
                unsigned: false
            nullable: false
            type: text
            length: 0
        remarks:
            options:
                comment: 备注
                unsigned: false
            nullable: false
            type: string
            length: 255
        ips:
            options:
                comment: IP集
                unsigned: false
            nullable: false
            type: string
            length: 100
        status:
            options:
                comment: '是否启用0否,1是'
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
