HouseBundle\Entity\AuthRule:
    type: entity
    table: auth_rule
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 规则中文名称
                unsigned: false
            nullable: false
            type: string
            length: 100
        type:
            options:
                comment: 分类
                unsigned: false
            nullable: false
            type: integer
            length: 3
        status:
            options:
                comment: 状态
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        conditions:
            options:
                comment: 规则表达式
                unsigned: false
            nullable: false
            type: text
            length: 0
        bundle:
            options:
                comment: 所属的Bundle
                unsigned: false
            nullable: false
            type: string
            length: 100
        controller:
            options:
                comment: 所属控制器
                unsigned: false
            nullable: false
            type: string
            length: 100
        action:
            options:
                comment: 方法动作
                unsigned: false
            nullable: false
            type: string
            length: 100
        menuid:
            options:
                comment: 菜单ID
                unsigned: false
            nullable: false
            type: integer
            length: 10
        pmenuid:
            options:
                comment: 上级菜单ID
                unsigned: false
            nullable: false
            type: integer
            length: 10
        identities:
            options:
                comment: 规则唯一标识
                unsigned: false
            nullable: false
            type: string
            length: 100
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
