HouseBundle\Entity\Build:
    type: entity
    table: build
    indexes:
        cate_status:
            columns:
                - cate_status
        aid:
            columns:
                - aid
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 楼栋
                unsigned: false
            nullable: false
            type: string
            length: 100
        zxcd:
            options:
                comment: 装修程度
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        cate_status:
            options:
                comment: 销售状态
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        dongtai:
            options:
                comment: 动态
                unsigned: false
            nullable: false
            type: string
            length: 100
        unit:
            options:
                comment: 单元
                unsigned: false
            nullable: false
            type: integer
            length: 100
        floor:
            options:
                comment: 层数
                unsigned: false
            nullable: false
            type: integer
            length: 100
        hushu:
            options:
                comment: 户数
                unsigned: false
            nullable: false
            type: integer
            length: 100
        kpsj:
            options:
                comment: 开盘时间
                unsigned: false
            nullable: false
            type: date
            length: 10
        jfsj:
            options:
                comment: 交房时间
                unsigned: false
            nullable: false
            type: date
            length: 10
        sgjd:
            options:
                comment: 施工进度
                unsigned: false
            nullable: false
            type: string
            length: 100
        xkzh:
            options:
                comment: 许可证号
                unsigned: false
            nullable: false
            type: string
            length: 100
        shapan:
            options:
                comment: 沙盘
                unsigned: false
            nullable: false
            type: string
            length: 100
        aid:
            options:
                comment: 文档id
                unsigned: false
            nullable: false
            type: integer
            length: 100
        models:
            options:
                comment: 模型
                unsigned: false
            nullable: false
            type: string
            length: 100
        uid:
            options:
                comment: 用户id
                unsigned: false
            nullable: false
            type: integer
            length: 100
        seat:
            options:
                comment: 楼栋坐标
                unsigned: false
            nullable: false
            type: string
            length: 100
        xkzh_time:
            options:
                comment: 许可证时间
                unsigned: false
            nullable: false
            type: date
            length: 10
        build_year:
            options:
                comment: 建筑年代
                unsigned: false
            nullable: false
            type: string
            length: 50
        house_num:
            options:
                comment: 房源数量
                unsigned: false
            nullable: false
            type: integer
            length: 11
        vacancy_floor:
            options:
                comment: 空缺楼层
                unsigned: false
            nullable: false
            type: string
            length: 100
        elevator:
            options:
                comment: 电梯数量
                unsigned: false
            nullable: false
            type: integer
            length: 11
        door_id:
            options:
                comment: 所属户型
                unsigned: false
            nullable: false
            type: string
            length: 50
        build_type:
            options:
                comment: 建筑类型
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        ladder:
            options:
                comment: 梯户比
                unsigned: false
            nullable: false
            type: string
            length: 100
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
