HouseBundle\Entity\Cron:
    type: entity
    table: cron
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 任务名称
                unsigned: false
            nullable: false
            type: string
            length: 50
        service_name:
            options:
                comment: 服务任务
                unsigned: false
            nullable: false
            type: string
            length: 50
        count:
            options:
                comment: 剩余执行次数
                unsigned: false
            nullable: false
            type: integer
            length: 10
        nextrun:
            options:
                comment: 下次执行时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        weekday:
            options:
                comment: 每周
                unsigned: false
            nullable: false
            type: smallint
            length: 1
        day:
            options:
                comment: 每日
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        hour:
            options:
                comment: 小时
                unsigned: false
            nullable: false
            type: string
            length: 36
        minute:
            options:
                comment: 分钟
                unsigned: false
            nullable: false
            type: string
            length: 36
        status:
            options:
                comment: '状态 1:启用 0:禁止'
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        model:
            options:
                comment: 模型
                unsigned: false
            nullable: false
            type: string
            length: 48
        mid:
            options:
                comment: 对应model数据的id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        type:
            options:
                comment: 分类
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
