HouseBundle\Entity\Demand:
    type: entity
    table: demand
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        tel:
            options:
                comment: 联系电话
                unsigned: false
            nullable: false
            type: string
            length: 100
        xingming:
            options:
                comment: 联系人
                unsigned: false
            nullable: false
            type: string
            length: 100
        mj:
            options:
                comment: 面积
                unsigned: false
            nullable: false
            type: float
            length: 100
        zj:
            options:
                comment: 价格
                unsigned: false
            nullable: false
            type: float
            length: 100
        jtyq:
            options:
                comment: 具体要求
                unsigned: false
            nullable: false
            type: string
            length: 100
        type:
            options:
                comment: '类别1:求购 2求租'
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        models:
            options:
                comment: 模型
                unsigned: false
                default: demand
            nullable: false
            default: demand
            type: string
            length: 100
        uid:
            options:
                comment: 会员id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        keywords:
            options:
                comment: 关键词
                unsigned: false
            nullable: false
            type: text
            length: 0
        description:
            options:
                comment: 描述
                unsigned: false
            nullable: false
            type: text
            length: 0
        area:
            options:
                comment: 区域
                unsigned: false
            nullable: false
            type: integer
            length: 10
        enddate:
            options:
                comment: 过期时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        region:
            options:
                comment: 区域
                unsigned: false
            nullable: false
            type: integer
            length: 100
        valid:
            options:
                comment: 上下架
                unsigned: false
            nullable: false
            type: integer
            length: 10
        category:
            options:
                comment: 求租求购类型
                unsigned: false
            nullable: false
            type: integer
            length: 10
        shi:
            options:
                comment: 室
                unsigned: false
            nullable: false
            type: integer
            length: 10
        ting:
            options:
                comment: 厅
                unsigned: false
            nullable: false
            type: integer
            length: 10
        huxing:
            options:
                comment: 户型
                unsigned: false
            nullable: false
            type: string
            length: 100
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
