HouseBundle\Entity\Files:
    type: entity
    table: files
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        token:
            options:
                comment: token
                unsigned: false
            nullable: false
            type: string
            length: 50
        url:
            options:
                comment: url路径
                unsigned: false
            nullable: false
            type: string
            length: 200
        size:
            options:
                comment: 文件大小
                unsigned: false
            nullable: false
            type: integer
            length: 10
        media_id:
            options:
                comment: 同步关联media
                unsigned: false
            nullable: false
            type: string
            length: 100
        type:
            options:
                comment: 文件类型
                unsigned: false
            nullable: false
            type: string
            length: 20
        name:
            options:
                comment: name
                unsigned: false
            nullable: false
            type: string
            length: 100
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: string
            length: 5
        filetype:
            options:
                comment: 文件类型
                unsigned: false
            nullable: false
            type: string
            length: 100
        is_sync:
            options:
                comment: 是否同步
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
