HouseBundle\Entity\InterAlbum:
    type: entity
    table: inter_album
    indexes:
        aid:
            columns:
                - aid
        uid:
            columns:
                - uid
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        cate_album:
            options:
                comment: 栏目
                unsigned: false
            nullable: false
            type: integer
            length: 10
        thumb:
            options:
                comment: 缩略图
                unsigned: false
            nullable: false
            type: text
            length: 0
        aid:
            options:
                comment: 文档id
                unsigned: false
            nullable: false
            type: integer
            length: 100
        models:
            options:
                comment: 模型
                unsigned: false
            nullable: false
            type: string
            length: 100
        cate_pushs:
            options:
                comment: 标识
                unsigned: false
            nullable: false
            type: string
            length: 100
        uid:
            options:
                comment: 用户id
                unsigned: false
            nullable: false
            type: integer
            length: 100
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
