HouseBundle\Entity\InterComment:
    type: entity
    table: inter_comment
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        aid:
            options:
                comment: 文档id
                unsigned: false
            nullable: false
            type: integer
            length: 11
        toid:
            options:
                comment: 被评论的id
                unsigned: false
            nullable: false
            type: integer
            length: 11
        vote:
            options:
                comment: 赞
                unsigned: false
            nullable: false
            type: integer
            length: 11
        thumb:
            options:
                comment: 头像
                unsigned: false
            nullable: false
            type: text
            length: 0
        uid:
            options:
                comment: 用户id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        models:
            options:
                comment: 模型
                unsigned: false
            nullable: false
            type: string
            length: 100
        content:
            options:
                comment: 内容
                unsigned: false
            nullable: false
            type: text
            length: 0
        user_agent:
            options:
                comment: 浏览器标识
                unsigned: false
            nullable: false
            type: text
            length: 0
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
