HouseBundle\Entity\InterHousescomment:
    type: entity
    table: inter_housescomment
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        content:
            options:
                comment: 内容
                unsigned: false
            nullable: false
            type: text
            length: 0
        overall:
            options:
                comment: 综合评分
                unsigned: false
            nullable: false
            type: string
            length: 100
        environment:
            options:
                comment: 环境
                unsigned: false
            nullable: false
            type: string
            length: 100
        charms:
            options:
                comment: 环境
                unsigned: false
            nullable: false
            type: string
            length: 100
        traffic:
            options:
                comment: 交通
                unsigned: false
            nullable: false
            type: string
            length: 100
        position:
            options:
                comment: 地段
                unsigned: false
            nullable: false
            type: string
            length: 100
        price:
            options:
                comment: 价格
                unsigned: false
            nullable: false
            type: string
            length: 100
        aid:
            options:
                comment: 楼盘ID
                unsigned: false
            nullable: false
            type: string
            length: 100
        uid:
            options:
                comment: 会员ID
                unsigned: false
            nullable: false
            type: string
            length: 100
        area:
            options:
                comment: 地区
                unsigned: false
            nullable: false
            type: string
            length: 100
        name:
            options:
                comment: 标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        toid:
            options:
                comment: 回复ID
                unsigned: false
            nullable: false
            type: string
            length: 100
        models:
            options:
                comment: 文档模型
                unsigned: false
            nullable: false
            type: string
            length: 100
        vote:
            options:
                comment: 支持数
                unsigned: false
            nullable: false
            type: string
            length: 100
        user_agent:
            options:
                comment: 浏览器标识
                unsigned: false
            nullable: false
            type: text
            length: 0
        source:
            options:
                comment: 来源
                unsigned: false
            nullable: false
            type: string
            length: 100
        comment_type:
            options:
                comment: 分类
                unsigned: false
            nullable: false
            type: integer
            length: 11
        nickename:
            options:
                comment: 昵称
                unsigned: false
            nullable: false
            type: string
            length: 100
        comment_source:
            options:
                comment: 评论来源
                unsigned: false
            nullable: false
            type: string
            length: 100
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
