HouseBundle\Entity\Loupandongtai:
    type: entity
    table: loupandongtai
    indexes:
        category_id:
            columns:
                - category_id
        aid:
            columns:
                - aid
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        category_id:
            options:
                comment: '(手动设置) 1: 楼盘动态 2: 预售证 3: 开盘信息 3: 交易信息'
                unsigned: false
                default: '1'
            nullable: false
            default: '1'
            type: smallint
            length: 2
        name:
            options:
                comment: 动态标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        content:
            options:
                comment: 动态内容
                unsigned: false
            nullable: false
            type: text
            length: 0
        aid:
            options:
                comment: 楼盘id
                unsigned: false
            nullable: false
            type: integer
            length: 100
        uid:
            options:
                comment: 用户id
                unsigned: false
            nullable: false
            type: integer
            length: 100
        day_date:
            options:
                comment: 时间
                unsigned: false
            nullable: false
            type: date
            length: 10
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
