HouseBundle\Entity\Memconfig:
    type: entity
    table: memconfig
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 规则标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        enable:
            options:
                comment: 是否启用
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        money:
            options:
                comment: 金额
                unsigned: false
            nullable: false
            type: float
            length: 100
        duedate:
            options:
                comment: 有效期
                unsigned: false
            nullable: false
            type: integer
            length: 10
        tops:
            options:
                comment: 赠送置顶天数
                unsigned: false
            nullable: false
            type: integer
            length: 10
        refreshs:
            options:
                comment: 赠送刷新次数
                unsigned: false
            nullable: false
            type: integer
            length: 10
        issystem:
            options:
                comment: '0为可删除 1为不可删除'
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        mem_group:
            options:
                comment: 会员组id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
