HouseBundle\Entity\Models:
    type: entity
    table: models
    indexes:
        name:
            columns:
                - name
        service_name:
            columns:
                - service_name
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 模型标识
                unsigned: false
            nullable: false
            type: string
            length: 50
        title:
            options:
                comment: 模型名称
                unsigned: false
            nullable: false
            type: string
            length: 50
        service_name:
            options:
                comment: 服务名称
                unsigned: false
            nullable: false
            type: string
            length: 100
        bundle:
            options:
                comment: 所属bundle
                unsigned: false
            nullable: false
            type: string
            length: 100
        relation:
            options:
                comment: 继承与被继承模型的关联字段
                unsigned: false
            nullable: false
            type: string
            length: 100
        search_key:
            options:
                comment: 默认搜索字段
                unsigned: false
            nullable: false
            type: string
            length: 100
        search_list:
            options:
                comment: 高级搜索的字段
                unsigned: false
            nullable: false
            type: string
            length: 100
        engine_type:
            options:
                comment: 数据库引擎
                unsigned: false
                default: MyISAM
            nullable: false
            default: MyISAM
            type: string
            length: 100
        status:
            options:
                comment: 状态
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: smallint
            length: 5
        autoup:
            options:
                comment: '是否自动重置0否,1是'
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        mode:
            options:
                comment: 模式
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        type:
            options:
                comment: 类型
                unsigned: false
            nullable: false
            type: smallint
            length: 3
        is_binary:
            options:
                comment: 是否启用二叉树
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        associated:
            options:
                comment: 关联字段
                unsigned: false
            nullable: false
            type: string
            length: 255
        structure:
            options:
                comment: '0横表,1纵表'
                unsigned: false
            nullable: false
            type: smallint
            length: 3
        attribute_table:
            options:
                comment: 属性表
                unsigned: false
            nullable: false
            type: integer
            length: 10
        models_plan:
            options:
                comment: 方案ID
                unsigned: false
            nullable: false
            type: integer
            length: 6
        checked:
            options:
                comment: 启用
                unsigned: false
                default: '1'
            nullable: false
            default: '1'
            type: boolean
            length: 1
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
