HouseBundle\Entity\Orderlist:
    type: entity
    table: orderlist
    indexes:
        ordersn:
            columns:
                - ordersn
        paytype:
            columns:
                - paytype
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        ordersn:
            options:
                comment: 订单编号
                unsigned: false
            nullable: false
            type: string
            length: 30
        paytype:
            options:
                comment: 交易工具
                unsigned: false
            nullable: false
            type: smallint
            length: 3
        total_fee:
            options:
                comment: 交易金额
                unsigned: false
            nullable: false
            type: float
            length: 12
        trade_status:
            options:
                comment: 交易状态
                unsigned: false
            nullable: false
            type: string
            length: 100
        status:
            options:
                comment: 订单状态
                unsigned: false
            nullable: false
            type: smallint
            length: 1
        conditions:
            options:
                comment: 条件集
                unsigned: false
            nullable: false
            type: text
            length: 0
        notify_time:
            options:
                comment: 通知的发送时间
                unsigned: false
            nullable: false
            type: string
            length: 50
        trade_no:
            options:
                comment: 支付工具交易id
                unsigned: false
            nullable: false
            type: string
            length: 30
        buyer_email:
            options:
                comment: 买家信息/邮箱
                unsigned: false
            nullable: false
            type: string
            length: 100
        paying:
            options:
                comment: 是否余额支付
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        uid:
            options:
                comment: 用户ID
                unsigned: false
            nullable: false
            type: integer
            length: 10
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
