HouseBundle\Entity\Showingsnews:
    type: entity
    table: showingsnews
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        topic:
            options:
                comment: 看房团id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        username:
            options:
                comment: 姓名
                unsigned: false
            nullable: false
            type: string
            length: 100
        phone:
            options:
                comment: 电话
                unsigned: false
            nullable: false
            type: string
            length: 20
        intention:
            options:
                comment: 意向楼盘
                unsigned: false
            nullable: false
            type: string
            length: 100
        content:
            options:
                comment: 备注
                unsigned: false
            nullable: false
            type: text
            length: 0
        name:
            options:
                comment: 标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        user_agent:
            options:
                comment: 浏览器类型
                unsigned: false
            nullable: false
            type: text
            length: 0
        models:
            options:
                comment: 模型
                unsigned: false
            nullable: false
            type: string
            length: 100
        mail:
            options:
                comment: 邮件
                unsigned: false
            nullable: false
            type: string
            length: 100
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
