HouseBundle\Entity\Sitemap:
    type: entity
    table: sitemap
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: Sitemap编号
                unsigned: false
            nullable: false
            type: string
            length: 20
        cname:
            options:
                comment: Sitemap名称
                unsigned: false
            nullable: false
            type: string
            length: 50
        xml_url:
            options:
                comment: XMLl调用链接
                unsigned: false
            nullable: false
            type: string
            length: 255
        status:
            options:
                comment: 是否有效
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: smallint
            length: 5
        issystem:
            options:
                comment: 是否系统Sitemap
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        tpl:
            options:
                comment: 模板文件
                unsigned: false
            nullable: false
            type: string
            length: 255
        ttl:
            options:
                comment: 更新周期(小时)
                unsigned: false
            nullable: false
            type: integer
            length: 10
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
