HouseBundle\Entity\Smstpls:
    type: entity
    table: smstpls
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        tid:
            options:
                comment: 标识ID
                unsigned: false
            nullable: false
            type: string
            length: 24
        name:
            options:
                comment: 模版名称
                unsigned: false
            nullable: false
            type: string
            length: 24
        tpl:
            options:
                comment: 模版内容
                unsigned: false
            nullable: false
            type: string
            length: 120
        checked:
            options:
                comment: 开启状态
                unsigned: false
                default: '1'
            nullable: false
            default: '1'
            type: smallint
            length: 2
        issystem:
            options:
                comment: '0为可删除 1为不可删除'
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        ename:
            options:
                comment: 调用标识
                unsigned: false
            nullable: false
            type: string
            length: 100
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
