HouseBundle\Entity\Special:
    type: entity
    table: special
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        aid:
            options:
                comment: 文档id
                unsigned: false
            nullable: false
            type: integer
            length: 100
        lpmc:
            options:
                comment: 楼盘名称
                unsigned: false
            nullable: false
            type: string
            length: 100
        uid:
            options:
                comment: 用户id
                unsigned: false
            nullable: false
            type: integer
            length: 100
        models:
            options:
                comment: 模型
                unsigned: false
            nullable: false
            type: string
            length: 100
        keywords:
            options:
                comment: 关键词
                unsigned: false
            nullable: false
            type: string
            length: 100
        abstract:
            options:
                comment: 摘要
                unsigned: false
            nullable: false
            type: string
            length: 100
        region:
            options:
                comment: 区域
                unsigned: false
            nullable: false
            type: integer
            length: 100
        cate_circle:
            options:
                comment: 商圈
                unsigned: false
            nullable: false
            type: integer
            length: 100
        cate_line:
            options:
                comment: 地铁
                unsigned: false
            nullable: false
            type: integer
            length: 100
        cate_metro:
            options:
                comment: 地铁站
                unsigned: false
            nullable: false
            type: integer
            length: 100
        area:
            options:
                comment: 分站
                unsigned: false
            nullable: false
            type: integer
            length: 100
        lh:
            options:
                comment: 楼号
                unsigned: false
            nullable: false
            type: string
            length: 100
        fh:
            options:
                comment: 房号
                unsigned: false
            nullable: false
            type: string
            length: 100
        dj:
            options:
                comment: 单价
                unsigned: false
            nullable: false
            type: float
            length: 100
        mj:
            options:
                comment: 面积
                unsigned: false
            nullable: false
            type: float
            length: 100
        zj:
            options:
                comment: 总价
                unsigned: false
            nullable: false
            type: float
            length: 100
        yj:
            options:
                comment: 原价
                unsigned: false
            nullable: false
            type: float
            length: 100
        shi:
            options:
                comment: 室
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        ting:
            options:
                comment: 厅
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        wei:
            options:
                comment: 卫
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        chu:
            options:
                comment: 厨
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        yangtai:
            options:
                comment: 阳台
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        zxcd:
            options:
                comment: 装修程度
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        cx:
            options:
                comment: 朝向
                unsigned: false
            nullable: false
            type: integer
            length: 10
        szlc:
            options:
                comment: 所在楼层
                unsigned: false
            nullable: false
            type: string
            length: 100
        zlc:
            options:
                comment: 总楼层
                unsigned: false
            nullable: false
            type: string
            length: 100
        louxing:
            options:
                comment: 楼型
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        cate_status:
            options:
                comment: 销售状态
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        thumb:
            options:
                comment: 缩略图
                unsigned: false
            nullable: false
            type: text
            length: 0
        xingming:
            options:
                comment: 联系人
                unsigned: false
            nullable: false
            type: string
            length: 100
        tel:
            options:
                comment: 联系电话
                unsigned: false
            nullable: false
            type: string
            length: 100
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
