HouseBundle\Entity\UserOauth:
    type: entity
    table: user_oauth
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        type:
            options:
                comment: 认证类型
                unsigned: false
            nullable: false
            type: string
            length: 100
        uid:
            options:
                comment: 所属用户
                unsigned: false
            nullable: false
            type: integer
            length: 10
        nickname:
            options:
                comment: 昵称
                unsigned: false
            nullable: false
            type: string
            length: 100
        realname:
            options:
                comment: 真实名称
                unsigned: false
            nullable: false
            type: string
            length: 100
        email:
            options:
                comment: email
                unsigned: false
            nullable: false
            type: string
            length: 100
        extend:
            options:
                comment: 扩展属性
                unsigned: false
            nullable: false
            type: text
            length: 0
        headimage:
            options:
                comment: 头像
                unsigned: false
            nullable: false
            type: string
            length: 255
        location:
            options:
                comment: 地理位置
                unsigned: false
            nullable: false
            type: string
            length: 64
        oauthid:
            options:
                comment: 唯一的识别id
                unsigned: false
            nullable: false
            type: string
            length: 128
        accessToken:
            options:
                comment: accessToken
                unsigned: false
            nullable: false
            type: string
            length: 100
        expiresIn:
            options:
                comment: 有效时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        tokenSecret:
            options:
                comment: tokenSecret
                unsigned: false
            nullable: false
            type: string
            length: 100
        unionid:
            options:
                comment: 用户唯一标识
                unsigned: false
            nullable: false
            type: string
            length: 50
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
