HouseBundle\Entity\Userconfig:
    type: entity
    table: userconfig
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        rentalperiod:
            options:
                comment: 租售有效期
                unsigned: false
            nullable: false
            type: integer
            length: 10
        rentdrenum:
            options:
                comment: 租售日发布数
                unsigned: false
            nullable: false
            type: integer
            length: 10
        drefresh:
            options:
                comment: 每日刷新次数
                unsigned: false
            nullable: false
            type: integer
            length: 10
        demandrenum:
            options:
                comment: 需求发布数量
                unsigned: false
            nullable: false
            type: integer
            length: 10
        demandqx:
            options:
                comment: 需求有效期限
                unsigned: false
            nullable: false
            type: integer
            length: 10
        role:
            options:
                comment: 会员角色
                unsigned: false
            nullable: false
            type: string
            length: 100
        issystem:
            options:
                comment: '0为可删除 1为不可删除'
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
