HouseBundle\Entity\Wxshakearound:
    type: entity
    table: wxshakearound
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        deviceid:
            options:
                comment: 设备ID
                unsigned: false
            nullable: false
            type: string
            length: 50
        devicetitle:
            options:
                comment: 设备名称
                unsigned: false
            nullable: false
            type: string
            length: 50
        uuid:
            options:
                comment: UUID
                unsigned: false
            nullable: false
            type: string
            length: 100
        major:
            options:
                comment: major
                unsigned: false
            nullable: false
            type: string
            length: 50
        minor:
            options:
                comment: minor
                unsigned: false
            nullable: false
            type: string
            length: 50
        status:
            options:
                comment: 状态
                unsigned: false
            nullable: false
            type: smallint
            length: 2
        title:
            options:
                comment: 页面主标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        description:
            options:
                comment: 页面副标题
                unsigned: false
            nullable: false
            type: string
            length: 100
        icon_url:
            options:
                comment: 摇一摇页面展示的图片
                unsigned: false
            nullable: false
            type: string
            length: 100
        page_url:
            options:
                comment: 跳转URL
                unsigned: false
            nullable: false
            type: string
            length: 100
        comment:
            options:
                comment: 备注信息
                unsigned: false
            nullable: false
            type: text
            length: 1000
        authtest:
            options:
                comment: 测试模型id
                unsigned: false
            nullable: false
            type: integer
            length: 10
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 100
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
