info:
    tableName: language
    subTableName: ''
    aliasName: p
    listGrid: {  }
    listDesc: ''
    subJoinField: ''
    storagetype: 3
    pageIndex: 1
    pageSize: 8
    groupBy: ''
    order: id
    orderBy: desc
    searchFun: EXISTS
    dataModel: 0
    attribute: '0'
    autoQuery: '1'
    alias: {  }
    query:
        ename:
            neq: _null
        name:
            orX: 'name,like,%[name]%'
    query1: {  }
