info:
    tableName: area
    subTableName: ''
    aliasName: p
    listGrid: {  }
    listDesc: ''
    subJoinField: ''
    storagetype: 3
    pageIndex: 1
    pageSize: 8
    groupBy: ''
    order: ''
    orderBy: asc
    searchFun: EXISTS
    dataModel: 0
    autoQuery: '0'
    alias: {  }
    query:
        type:
            eq: '1'
        id:
            eq: '<area>'
    query1: {  }
