views:
    tableName: views
    aliasName: p
    storagetype: 1
    pageIndex: 1
    pageSize: 8
    order: ''
    orderBy: asc
    alias:
        t1: name
        t2: bundle
        t3: controller
        t4: title
    join:
        menus:
            aliasName: pp
            joinType: join
            alias:
                t5: name
            query:
                pid:
                    eq: p.id
        models:
            aliasName: ppp
            joinType: join
            alias:
                t6: name
                t7: title
            query:
                id:
                    eq: p.id
